spring:
  jackson:
    default-property-inclusion: NON_NULL

springdoc:
  default-produces-media-type: application/json

management:
  endpoints:
    web:
      exposure:
        include: health,info,mappings,metrics
